# Generated by Django 4.2.7 on 2023-11-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_imagen',
            field=models.URLField(default='https://ejemplo.com/imagen_por_defecto.jpg', max_length=300),
        ),
    ]
