# Generated by Django 4.2.7 on 2025-10-31 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_producto_marca_producto_talla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('WEBPAY', 'WebPay'), ('EFECTIVO', 'Efectivo en tienda')], default='TRANSFERENCIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('subtotal', models.IntegerField()),
                ('costo_envio', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Aplicacion.cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=100)),
                ('producto_descripcion', models.CharField(blank=True, max_length=200)),
                ('producto_imagen', models.URLField(max_length=400)),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Aplicacion.orden')),
            ],
        ),
    ]
