# Generated by Django 4.2.7 on 2025-11-21 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_orden_itemorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(5000000)]),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orden',
            name='costo_envio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(5000000)]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(5000000)]),
        ),
    ]
